@"
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd front
      - npm ci
  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  base-directory: front/out
  files:
    - '**/*'
"@ | Set-Content -Encoding utf8 buildspec.yml
