version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - cd front
      - npm ci

  build:
    commands:
      - echo "NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL"
      - printenv | grep NEXT_PUBLIC_API_BASE_URL || true
      - node -e "console.log('node sees:', process.env.NEXT_PUBLIC_API_BASE_URL)"
      - npm run build
      - ls -al out

artifacts:
  base-directory: front/out
  files:
    - '**/*'
  discard-paths: no






# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20

#   pre_build:
#     commands:
#       - cd front
#       - npm ci

#   build:
#     commands:
#       - npm run build

# artifacts:
#   base-directory: front
#   files:
#     - .next/**/*
#     - public/**/*
#     - package.json
#     - package-lock.json
#     - next.config.js
#     - appspec.yml
#     - scripts/**/*
