version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd front
      - npm ci

  build:
    commands:
      - echo "NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL"
      - printenv | grep NEXT_PUBLIC_API_BASE_URL || true
      - npm run build
      - echo "=== search localhost in out ==="
      - grep -R "localhost:8080" -n out || true
      - echo "=== search backend domain in out ==="
      - grep -R "<백엔드실도메인>" -n out || true

artifacts:
  base-directory: front/out
  files:
    - "**/*"







# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20

#   pre_build:
#     commands:
#       - cd front
#       - npm ci

#   build:
#     commands:
#       - npm run build

# artifacts:
#   base-directory: front
#   files:
#     - .next/**/*
#     - public/**/*
#     - package.json
#     - package-lock.json
#     - next.config.js
#     - appspec.yml
#     - scripts/**/*
